CREATE DATABASE pi;

USE pi;

CREATE TABLE cliente (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nomeCompleto VARCHAR(50) NOT NULL,
	cpf VARCHAR(11) NOT NULL UNIQUE,
    dataNasc VARCHAR(10) NOT NULL,
    email VARCHAR(50) NOT NULL,
    senha VARCHAR(20) NOT NULL,
    sexo VARCHAR(10) NOT NULL,
    endereco VARCHAR(50) NOT NULL, 
    complemento VARCHAR(10),
    formaPagamento VARCHAR(20) NOT NULL
);

CREATE TABLE produto (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL UNIQUE,
	tamanho VARCHAR(10) NOT NULL,
    preco DOUBLE NOT NULL,
    qtdEstoque INTEGER NOT NULL,
    categoria VARCHAR(10) NOT NULL
);
